import:
- logstash-plugins/.ci:travis/travis.yml@1.x

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/redis-server'
    packages:
      - redis-server

#before_install: # Redis tried to bind to ::1 but IPv6 isn't supported
#  - sudo service redis-server stop || true
#  - sudo service redis-server start --bind 127.0.0.1
